### ISSUE TITLE
NullPointerException when creating Card Image

### ISSUE THREAD

**Issue by Tiagocf2** [Alchyr/BasicMod#1]
I was following along with the tutorial and it was going alright until i tried adding a card.
I literally copied the code and it still crashed :(

```
java.lang.NullPointerException
	at basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.CreateCardImageSwitch$CreateCardImage.Prefix(CreateCardImageSwitch.java:24)
	at com.megacrit.cardcrawl.cards.AbstractCard.createCardImage(AbstractCard.java)
	at com.megacrit.cardcrawl.cards.AbstractCard.<init>(AbstractCard.java:391)
	at com.megacrit.cardcrawl.cards.AbstractCard.<init>(AbstractCard.java:322)
	at basemod.abstracts.CustomCard.<init>(CustomCard.java:89)
	at illaoimod.cards.BaseCard.<init>(BaseCard.java:49)
	at illaoimod.cards.BaseCard.<init>(BaseCard.java:40)
	at illaoimod.cards.Strike.<init>(Strike.java:29)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at basemod.AutoAdd.any(AutoAdd.java:130)
	at basemod.AutoAdd.cards(AutoAdd.java:140)
	at illaoimod.IllaoiMod.receiveEditCards(IllaoiMod.java:209)
	at basemod.BaseMod.publishEditCards(BaseMod.java:2484)
	at basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.EditCardsPatch.Prefix(EditCardsPatch.java:11)
	at com.megacrit.cardcrawl.helpers.CardLibrary.initialize(CardLibrary.java)
	at com.megacrit.cardcrawl.core.CardCrawlGame.create(CardCrawlGame.java:282)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:149)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
	```

**Comment by Alchyr** [comment]
To crash on that line, it means that your card color isn't registered with BaseMod, which would be [this step](https://github.com/Alchyr/BasicMod/wiki/Adding-a-Character#color) of creating a character

Otherwise, the error could occur if you're using `null` when you register your color.
